# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'babyNameIOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'TextFieldEffects'
#  pod 'FBSDKCoreKit'
#  pod 'FBSDKLoginKit'
#  pod 'FBSDKShareKit'
  pod 'SDWebImage'
  pod 'Instabug'
  pod 'Alamofire', '~> 4.5'
  pod 'SwiftyJSON'
  pod 'MBProgressHUD', '~> 0.9'
  pod 'SwiftDate'
  pod 'lottie-ios'
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'
 
  pod 'UIColor+FlatColors'
  pod 'Cartography'
  target 'babyNameIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end



